### PR TITLE
add $CURSOR for position in zsh.sh script

### LINKED ISSUE #23: zsh.sh does not set cursor point/position (is always 0)
partial and lastPartial are computed using line and point. When point defaults to 0 partial and lastPartial can't be computed. By updating this script to provide a positional value we get parity with these 3 environment options relative to bash at least (I have not tested with fish, but at least as far as I can tell it appears to provide this value.)

### PR DESCRIPTION
**Pull request by binduwavell**
fixes #23

### CODE REVIEW

**Comment by mklabs** [comment]
Great! Could you update the test as well ? https://github.com/mklabs/node-tabtab/blob/master/test/complete.js#L19

We should probably add a bunch more to cover all possible cases you described in #25

I still need to improve the tests a lot more. I'd like to be able to programmatically trigger a tab completion but not sure how to do it, for now, we'll just tests stdout result.

**Comment by binduwavell** [comment]
You're existing tests pass and I only made zsh behave the same as bash, so I assumed for this commit I didn't have to write extra tests.

**Comment by mklabs** [comment]
oh, that's true :) Merging in this case.

Though I need to cover zsh too.

**Comment by mklabs** [comment]
Thanks again!

**Pull request merged**
